addons:
    postgresql: "9.4"
language: python
matrix:
    include:
        - python: "3.7"
          before_install: pip install -r requirements_buster.txt
        - python: "3.5"
          before_install: pip install -r requirements_stretch.txt
        - python: "3.4"
          before_install:
              - pip install --upgrade pip
              - pip install --upgrade setuptools "pytest==3.7.1"
              - pip install -r requirements_jessie.txt
install: "pip install codecov -e .[master,slave,logger,test]"
before_script:
    - psql -U postgres -c "create user piwheels password 'piwheels'"
    - psql -U postgres -c "create database piwheels_test"
script: make test
after_success:
    - codecov
